Update patch set 3
Patch Set 3:

Failed with

paladox@gerrit-test:~/gerrit$ bazel build plugins/branch-network
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
INFO: From Building gerrit-server/libserver.jar (1306 source files, 41 resources):
Note: gerrit-server/src/main/java/com/google/gerrit/server/api/changes/ChangeApiImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
ERROR: /home/paladox/gerrit/plugins/branch-network/BUILD:3:1: Java compilation in rule '//plugins/branch-network:branch-network__plugin' failed: Worker process sent response with exit code: 1.
plugins/branch-network/src/main/java/com/googlesource/gerrit/plugins/branchnetwork/canvas/GitGraphServlet.java:114: error: cannot find symbol
      GitwebType type = gitWebConfig.getGitwebType();
                                    ^
  symbol:   method getGitwebType()
  location: variable gitWebConfig of type GitwebConfig
plugins/branch-network/src/main/java/com/googlesource/gerrit/plugins/branchnetwork/data/GitCommitCacheRefresh.java:34: error: cannot find symbol
    this.repoManager = repoManager;
        ^
  symbol: variable repoManager
plugins/branch-network/src/main/java/com/googlesource/gerrit/plugins/branchnetwork/data/GitCommitCacheRefresh.java:34: error: cannot find symbol
    this.repoManager = repoManager;
                       ^
  symbol:   variable repoManager
  location: class GitCommitCacheRefresh
3 errors
Target //plugins/branch-network:branch-network failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 59.430s, Critical Path: 48.15s

@David Ostrovsky im wondering would you know how to fix this please?

The gitweb change was broken by https://github.com/gerrit-review/gerrit/commit/c4a90512d540041be5c256ce6aba1dae44b7aecf#diff-bbc1adecda45cb2e6ab44d1635a044b1

It changed it from a public to private function.

Patch-set: 3
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>